export const MENU_LEAGUE = [
    { name: "NFL",
      subnav: [ "Live Odds", "Futures", "Matchup", "Consensus" ],
      url: [ "", "futures", "matchups", "consensus" ] },
    { name: "MLB",
      subnav: [ "Live Odds", "Futures", "Matchup" ],
      url: [ "", "futures", "matchups" ] },
    { name: "NHL",
      subnav: [ "Live Odds", "Futures", "Matchup" ],
      url: [ "", "futures", "matchups" ] },
    { name: "NBA",
      subnav: [ "Live Odds", "Futures", "Matchup" ],
      url: [ "", "futures", "matchups" ] },
    { name: "NCAAB",
      subnav: [ "Live Odds", "Futures", "Matchup" ],
      url: [ "", "futures", "matchups" ] },
    { name: "NCAAF",
      subnav: [ "Live Odds", "Futures", "Matchup" ],
      url: [ "", "futures", "matchups" ] },
    { name: "MLS",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "BUNDESLIGA",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "CHAMPIONS-LEAGUE",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "EUROPA-LEAGUE",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "SERIE-A",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "LA-LIGA",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "LIGUE-1",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "PREMIER-LEAGUE",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "WNBA",
      subnav: [ "Live Odds" ],
      url: [ ""] },
    { name: "CFL",
      subnav: [ "Live Odds" ],
      url: [ ""] },
  ];

export const MENU_SPORTS = [ "Baseball", "Basketball", "Football", "Soccer", "Hockey"];

export const LEAGUE_HEADER = {
  "BUNDESLIGA": "Bundesliga",
  "CHAMPIONS-LEAGUE": "Champions League",
  "EUROPA-LEAGUE": "Europa League",
  "SERIE-A": "Serie A",
  "LA-LIGA": "La Liga",
  "LIGUE-1": "Ligue 1",
  "PREMIER-LEAGUE": "English Premier League",
}
