name: Release

on:
  release:
    types: [created]

jobs:
  sbr-stellar-components:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
        run: |
          cd packages/sbr-stellar-components
          npm install
          npm run build
          npm version patch
          npm publish

  sbr-stellar-design:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
        run: |
          cd packages/sbr-stellar-design
          npm install
          npm run build
          npm version patch
          npm publish
